# Fase 1: Data Pipeline
## Carga, Limpieza y Exportación de Datos

**Objetivo:** Cargar los 5 datasets crudos, aplicar limpieza y transformaciones, y exportar los datos procesados a `data/processed/`.

In [ ]:
import pandas as pd
import numpy as np
import sys
sys.path.append('..')
from src.data_loader import load_all_data
from src.cleaning import *
from src.visualization import set_style

set_style()

## 1. Cargar datos crudos

In [2]:
data = load_all_data()
editions = data['editions']
matches = data['matches']
top_scorers = data['top_scorers']
teams_2026 = data['teams_2026']
fixtures_2026 = data['fixtures_2026']

print('Editions:', editions.shape)
print('Matches:', matches.shape)
print('Top Scorers:', top_scorers.shape)
print('2026 Teams:', teams_2026.shape)
print('2026 Fixtures:', fixtures_2026.shape)

Editions: (22, 20)
Matches: (184, 11)
Top Scorers: (22, 11)
2026 Teams: (48, 7)
2026 Fixtures: (104, 15)

## Inspección de datos crudos

In [3]:
print('=== EDITIONS ===')
editions.info()
print('\n=== MATCHES ===')
matches.info()
print('\n=== TOP SCORERS ===')
top_scorers.info()
print('\n=== 2026 TEAMS ===')
teams_2026.info()
print('\n=== 2026 FIXTURES ===')
fixtures_2026.info()

=== EDITIONS ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   edition             22 non-null     int64
 1   year                22 non-null     int64
 2   host                22 non-null     object
 3   champion            22 non-null     object
 4   runner_up           22 non-null     object
 5   third_place         22 non-null     object
 6   fourth_place        22 non-null     object
 7   teams               22 non-null     int64
 8   matches             22 non-null     int64
 9   goals               22 non-null     int64
 10  goals_per_match     22 non-null     float64
 11  attendance          22 non-null     int64
 12  top_scorer          22 non-null     object
 13  top_scorer_country  22 non-null     object
 14  top_scorer_goals    22 non-null     int64
 15  start_date          22 non-null     object
 16  end_date            22 non-null     object
 17  final_city          22 non-null     object
 18  host_won            22 non-null     object
 19  format              22 non-null     object
dtypes: float64(1), int64(7), object(12)
memory usage: 3.6+ KB

=== MATCHES ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     184 non-null    int64
 1   stage    184 non-null    object
 2   team1    184 non-null    object
 3   score1   184 non-null    int64
 4   score2   184 non-null    int64
 5   team2    184 non-null    object
 6   venue    184 non-null    object
 7   city     184 non-null    object
 8   country  184 non-null    object
 9   date     184 non-null    object
 10  notes    102 non-null    object
dtypes: int64(3), object(8)
memory usage: 15.9+ KB

=== TOP SCORERS ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   edition         22 non-null     int64
 1   year            22 non-null     int64
 2   player          22 non-null     object
 3   country         22 non-null     object
 4   position        22 non-null     object
 5   goals           22 non-null     int64
 6   assists         22 non-null     int64
 7   penalties       22 non-null     int64
 8   matches_played  22 non-null     int64
 9   host            22 non-null     object
 10  team_result     22 non-null     object
dtypes: int64(6), object(5)
memory usage: 2.0+ KB

=== 2026 TEAMS ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   team            48 non-null     object
 1   group           48 non-null     object
 2   confederation   48 non-null     object
 3   fifa_rank       48 non-null     int64
 4   coach           48 non-null     object
 5   best_wc_result  48 non-null     object
 6   debut_2026      48 non-null     object
dtypes: int64(1), object(6)
memory usage: 2.8+ KB

=== 2026 FIXTURES ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     object
 1   stage                104 non-null    object
 2   team1                104 non-null    object
 3   team2                104 non-null    object
 4   venue                104 non-null    object
 5   city                 104 non-null    object
 6   country              104 non-null    object
 7   date                 104 non-null    object
 8   kickoff_et           104 non-null    object
 9   team1_confederation  72 non-null     object
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     object
 12  team2_confederation  72 non-null     object
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     object
dtypes: float64(2), object(13)
memory usage: 12.3+ KB

In [4]:
print('=== EDITIONS - Head ===')
display(editions.head())
print('\n=== MATCHES - Head ===')
display(matches.head())
print('\n=== TOP SCORERS - Head ===')
display(top_scorers.head())
print('\n=== 2026 TEAMS - Head ===')
display(teams_2026.head())
print('\n=== 2026 FIXTURES - Head ===')
display(fixtures_2026.head())

=== EDITIONS - Head ===

,edition,year,host,champion,runner_up,third_place,fourth_place,teams,matches,goals,goals_per_match,attendance,top_scorer,top_scorer_country,top_scorer_goals,start_date,end_date,final_city,host_won,format
0,1,1930,Uruguay,Uruguay,Argentina,United States,Yugoslavia,13,18,70,3.89,590549,Guillermo Stábile,Argentina,8,July 13,July 30,Montevideo,No,Round Robin
1,2,1934,Italy,Italy,Czechoslovakia,Germany,Austria,16,17,70,4.12,363000,Oldřich Nejedlý,Czechoslovakia,5,May 27,June 10,Rome,Yes,Knockout
2,3,1938,France,Italy,Hungary,Brazil,Sweden,15,18,84,4.67,375700,Leônidas,Brazil,7,June 4,June 19,Paris,Yes,Knockout
3,4,1950,Brazil,Uruguay,Brazil,Sweden,Spain,13,22,88,4.00,1045246,Ademir,Brazil,8,June 24,July 16,Rio de Janeiro,No,Round Robin Final
4,5,1954,Switzerland,West Germany,Hungary,Austria,Uruguay,16,26,140,5.38,768607,Sándor Kocsis,Hungary,11,June 16,July 4,Bern,No,Knockout

=== MATCHES - Head ===

,year,stage,team1,score1,score2,team2,venue,city,country,date,notes
0,1930,Group Stage,France,4,1,Mexico,Estadio Centenario,Montevideo,Uruguay,1930-07-13,First ever WC match
1,1930,Group Stage,USA,3,0,Belgium,Estadio Centenario,Montevideo,Uruguay,1930-07-13,NaN
2,1930,Group Stage,Yugoslavia,2,1,Brazil,Estadio Centenario,Montevideo,Uruguay,1930-07-14,NaN
3,1930,Group Stage,Uruguay,1,0,Peru,Estadio Centenario,Montevideo,Uruguay,1930-07-18,NaN
4,1930,Group Stage,Argentina,6,3,USA,Estadio Centenario,Montevideo,Uruguay,1930-07-26,NaN

=== TOP SCORERS - Head ===

,edition,year,player,country,position,goals,assists,penalties,matches_played,host,team_result
0,1,1930,Guillermo Stábile,Argentina,FW,8,0,0,4,Uruguay,Champions
1,2,1934,Oldřich Nejedlý,Czechoslovakia,FW,5,0,0,4,Italy,Semi-final
2,3,1938,Leônidas,Brazil,FW,7,0,0,5,France,Third place
3,4,1950,Ademir,Brazil,FW,8,0,0,6,Brazil,Runner-up
4,5,1954,Sándor Kocsis,Hungary,FW,11,0,0,5,Switzerland,Runner-up

=== 2026 TEAMS - Head ===

,team,group,confederation,fifa_rank,coach,best_wc_result,debut_2026
0,Mexico,A,CONCACAF,15,Javier Aguirre,"Quarter-finals (1970,1986)",No
1,South Africa,A,CAF,60,Hugo Broos,"Group stage (1998,2002,2010)",No
2,South Korea,A,AFC,25,Hong Myung-bo,Semi-finals (2002),No
3,Czechia,A,UEFA,41,Ivan Hasek,"Runner-up (1934,1962)",No
4,Canada,B,CONCACAF,30,Jesse Marsch,"Group stage (1986,2022)",No

=== 2026 FIXTURES - Head ===

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

## Aplicar limpieza

In [5]:
editions_clean = clean_editions(editions)
matches_clean = clean_matches(matches)
top_scorers_clean = clean_top_scorers(top_scorers)
teams_2026_clean = clean_2026_teams(teams_2026)
fixtures_2026_clean = clean_2026_fixtures(fixtures_2026)

print('Cleaning complete!')

Cleaning complete!

## Exportar datos limpios

In [6]:
editions_clean.to_csv('../data/processed/editions_clean.csv', index=False)
matches_clean.to_csv('../data/processed/matches_clean.csv', index=False)
top_scorers_clean.to_csv('../data/processed/top_scorers_clean.csv', index=False)
teams_2026_clean.to_csv('../data/processed/teams_2026_clean.csv', index=False)
fixtures_2026_clean.to_csv('../data/processed/fixtures_2026_clean.csv', index=False)

print('All cleaned datasets exported to data/processed/')

All cleaned datasets exported to data/processed/

## Verificación final

In [9]:
print('=== EDITIONS CLEAN ===')
display(editions_clean.head())
print(f'Shape: {editions_clean.shape}')
print(editions_clean.isnull().sum())
print(f'Nulls: {editions_clean.isnull().sum().sum()}')

print('\n=== MATCHES CLEAN ===')
display(matches_clean.head())
print(f'Shape: {matches_clean.shape}')
print(matches_clean.isnull().sum())
print(f'Nulls: {matches_clean.isnull().sum().sum()}')

print('\n=== TOP SCORERS CLEAN ===')
display(top_scorers_clean.head())
print(f'Shape: {top_scorers_clean.shape}')
print(top_scorers_clean.isnull().sum())
print(f'Nulls: {top_scorers_clean.isnull().sum().sum()}')

print('\n=== 2026 TEAMS CLEAN ===')
display(teams_2026_clean.head())
print(f'Shape: {teams_2026_clean.shape}')
print(teams_2026_clean.isnull().sum())
print(f'Nulls: {teams_2026_clean.isnull().sum().sum()}')

print('\n=== 2026 FIXTURES CLEAN ===')
display(fixtures_2026_clean.head())
print(f'Shape: {fixtures_2026_clean.shape}')
print(f'Nulls: {fixtures_2026_clean.isnull().sum().sum()}')
print(fixtures_2026_clean.isnull().sum())

=== EDITIONS CLEAN ===

,edition,year,host,champion,runner_up,third_place,fourth_place,teams,matches,goals,...,top_scorer_country,top_scorer_goals,start_date,end_date,final_city,host_won,format,host_won_bool,decade,attendance_per_match
0,1,1930,Uruguay,Uruguay,Argentina,United States,Serbia,13,18,70,...,Argentina,8,July 13,July 30,Montevideo,No,Round Robin,False,1930,32808
1,2,1934,Italy,Italy,Czechia,Germany,Austria,16,17,70,...,Czechoslovakia,5,May 27,June 10,Rome,Yes,Knockout,True,1930,21353
2,3,1938,France,Italy,Hungary,Brazil,Sweden,15,18,84,...,Brazil,7,June 4,June 19,Paris,Yes,Knockout,True,1930,20872
3,4,1950,Brazil,Uruguay,Brazil,Sweden,Spain,13,22,88,...,Brazil,8,June 24,July 16,Rio de Janeiro,No,Round Robin Final,False,1950,47511
4,5,1954,Switzerland,Germany,Hungary,Austria,Uruguay,16,26,140,...,Hungary,11,June 16,July 4,Bern,No,Knockout,False,1950,29562

Shape: (22, 23)
edition                 0
year                    0
host                    0
champion                0
runner_up               0
third_place             0
fourth_place            0
teams                   0
matches                 0
goals                   0
goals_per_match         0
attendance              0
top_scorer              0
top_scorer_country      0
top_scorer_goals        0
start_date              0
end_date                0
final_city              0
host_won                0
format                  0
host_won_bool           0
decade                  0
attendance_per_match    0
dtype: int64
Nulls: 0

=== MATCHES CLEAN ===

,year,stage,team1,score1,score2,team2,venue,city,country,date,notes,total_goals,goal_diff,is_knockout,is_group_stage,is_upset,has_extra_time,has_penalties,is_record
0,1930,Group Stage,France,4,1,Mexico,Estadio Centenario,Montevideo,Uruguay,1930-07-13,First ever WC match,5,3,False,True,False,False,False,True
1,1930,Group Stage,USA,3,0,Belgium,Estadio Centenario,Montevideo,Uruguay,1930-07-13,NaN,3,3,False,True,False,False,False,False
2,1930,Group Stage,Serbia,2,1,Brazil,Estadio Centenario,Montevideo,Uruguay,1930-07-14,NaN,3,1,False,True,False,False,False,False
3,1930,Group Stage,Uruguay,1,0,Peru,Estadio Centenario,Montevideo,Uruguay,1930-07-18,NaN,1,1,False,True,False,False,False,False
4,1930,Group Stage,Argentina,6,3,USA,Estadio Centenario,Montevideo,Uruguay,1930-07-26,NaN,9,3,False,True,False,False,False,False

Shape: (184, 19)
year               0
stage              0
team1              0
score1             0
score2             0
team2              0
venue              0
city               0
country            0
date               0
notes             82
total_goals        0
goal_diff          0
is_knockout        0
is_group_stage     0
is_upset           0
has_extra_time     0
has_penalties      0
is_record          0
dtype: int64
Nulls: 82

=== TOP SCORERS CLEAN ===

,edition,year,player,country,position,goals,assists,penalties,matches_played,host,team_result,goals_per_match,champion_scorer,is_multiple,decade
0,1,1930,Guillermo Stábile,Argentina,FW,8,0,0,4,Uruguay,Champions,2.00,True,False,1930
1,2,1934,Oldřich Nejedlý,Czechia,FW,5,0,0,4,Italy,Semi-final,1.25,False,False,1930
2,3,1938,Leônidas,Brazil,FW,7,0,0,5,France,Third place,1.40,False,False,1930
3,4,1950,Ademir,Brazil,FW,8,0,0,6,Brazil,Runner-up,1.33,False,False,1950
4,5,1954,Sándor Kocsis,Hungary,FW,11,0,0,5,Switzerland,Runner-up,2.20,False,False,1950

Shape: (22, 15)
edition            0
year               0
player             0
country            0
position           0
goals              0
assists            0
penalties          0
matches_played     0
host               0
team_result        0
goals_per_match    0
champion_scorer    0
is_multiple        0
decade             0
dtype: int64
Nulls: 0

=== 2026 TEAMS CLEAN ===

,team,group,confederation,fifa_rank,coach,best_wc_result,debut_2026,is_debutant,is_champion,best_round_numeric,fifa_rank_category
0,Mexico,A,CONCACAF,15,Javier Aguirre,"Quarter-finals (1970,1986)",No,False,False,3,High
1,South Africa,A,CAF,60,Hugo Broos,"Group stage (1998,2002,2010)",No,False,False,1,Medium
2,South Korea,A,AFC,25,Hong Myung-bo,Semi-finals (2002),No,False,False,4,High
3,Czechia,A,UEFA,41,Ivan Hasek,"Runner-up (1934,1962)",No,False,False,5,Medium
4,Canada,B,CONCACAF,30,Jesse Marsch,"Group stage (1986,2022)",No,False,False,1,High

Shape: (48, 11)
team                  0
group                 0
confederation         0
fifa_rank             0
coach                 0
best_wc_result        0
debut_2026            0
is_debutant           0
is_champion           0
best_round_numeric    0
fifa_rank_category    0
dtype: int64
Nulls: 0

=== 2026 FIXTURES CLEAN ===

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach,is_group_stage,is_knockout
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos,True,False
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek,True,False
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre,True,False
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos,True,False
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre,True,False

Shape: (104, 17)
Nulls: 224
group                  32
stage                   0
team1                   0
team2                   0
venue                   0
city                    0
country                 0
date                    0
kickoff_et              0
team1_confederation    32
team1_fifa_rank        32
team1_coach            32
team2_confederation    32
team2_fifa_rank        32
team2_coach            32
is_group_stage          0
is_knockout             0
dtype: int64

## Resumen

Todos los datasets han sido cargados, limpiados y exportados a `data/processed/`.
Los notebooks siguientes cargarán desde `data/processed/` directamente.